name: after-push checks
run-name: 4checks
on:
  workflow_dispatch:
  push:
jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install prospector[with_everything] pytest
          pip install kivy[base] kivy_examples --pre --extra-index-url https://kivy.org/downloads/simple/
                    pip install kivymd
      - name: linter
        run:
          prospector --profile .prospector.yaml
      - name: unit-tests
        run:
          pytest